TINY-9428: Code Scanning
tinymce/bedrock pull request #113
Opened 2022-11-30 09:59 UTC by spocke

Related Ticket: TINY-9428

Description of Changes:
* Added updated codeql file

2022-11-30 12:56 UTC, yacodes approved these changes

2022-11-30 15:02 UTC, ephox-mogran approved these changes

2022-12-01 00:34 UTC, shanmen-tiny approved these changes

2022-12-01 01:26 UTC, jscasca requested changes
Hey guys, this probably would cause a lot of repeated scanning. You could probably get away with only scanning on push and PRs to `master` and `release/**`. Otherwise, you are scanning when you push the branch and then re-scanning when you create the PR.
```
on:
  push:
    branches: [ "release/**", "master" ]
  pull_request:
    branches: [ "release/**", "master" ]
```

2022-12-01 05:52 UTC, spocke commented
> Hey guys, this probably would cause a lot of repeated scanning. You could probably get away with only scanning on push and PRs to `master` and `release/**`. Otherwise, you are scanning when you push the branch and then re-scanning when you create the PR.
> 
> ```
> on:
>   push:
>     branches: [ "release/**", "master" ]
>   pull_request:
>     branches: [ "release/**", "master" ]
> ```

I changed this and added "develop" as well since if we ever use that it will work as well it wouldn't hurt.

2022-12-02 06:53 UTC, merged