TINY-9855: fix for watch mode
tinymce/bedrock pull request #123
Opened 2023-06-01 14:04 UTC by lorenzo-pomili

Related Ticket: TINY-9855

Description of Changes:
the problem seems to be the 2 different version of `fork-ts-checker-webpack-plugin`

Pre-checks:
* [x] Changelog entry added
* [x] package.json version bumped (if first change of new major/minor)
* [x] ~Tests have been added (if applicable)~

Before merging:
* [ ] Ensure internal dependencies are on appropriate versions
  * For stable releases, all dependencies must be stable
  * For release candidates, all dependencies must be release candidates or stable

2023-06-02 03:50 UTC, vpyshnenko approved these changes

2023-06-07 23:16 UTC, TheSpyder requested changes
Shouldn't `yarn.lock` be updated as well? Don't tell me you just edited the `package.json` 😉

2023-06-08 06:06 UTC, lorenzo-pomili commented
@TheSpyder I thought that I just had a last test to see if putting the dependencies back to the original makes me reproduce the bug again but I think it is not the case.

There is something odd with the `yarn install`, it seems that `--install.frozen-lockfile true` is not working as expected, you are allowed to launch `yarn install` with different dependencies versions in sub-directories even if you have `--install.frozen-lockfile true` and the dependencies are downloaded at the correct version, but the `yarn.lock` file is not updated.

I launched `yarn install` without `--install.frozen-lockfile true` to update the `yarn.lock` (of course it has updated a lot of other dependencies too), I'll check to see if there is a way to make it works also in the sub-directory (I already try to add the `.yarnrc` also to the sub-directory)

2023-06-08 06:25 UTC, TheSpyder approved these changes
To update `yarn.lock` without turning off frozen lockfile you just need to use `yarn add` or `yarn upgrade-interactive` instead of editing the `package.json` by hand.

I'm not sure why yarn let itself run with such a huge disparity in version numbers. Normally it fails saying the lockfile needs to be updated.

2023-06-08 06:41 UTC, lorenzo-pomili commented
@TheSpyder I think it is related to the fact that it is not at the first level :/

2023-06-08 07:14 UTC, merged